name: Build

env:
  GODOT_VERSION: 4.5.1

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Godot
        run: |
          wget "https://downloads.godotengine.org/?version=${{ env.GODOT_VERSION }}&flavor=stable&slug=linux.x86_64.zip&platform=linux.64" -O godot.zip
          unzip godot.zip
          mv Godot_v*-stable_linux.x86_64 godot
          wget "https://downloads.godotengine.org/?version=${{ env.GODOT_VERSION }}&flavor=stable&slug=export_templates.tpz&platform=templates" -O templates.zip
          unzip templates.zip
          mkdir -p $HOME/.local/share/godot/export_templates/
          mv templates/ $HOME/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable/
      - name: Set GitHub Environment Variables
        run: |
          echo "GITHUB_SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Export Project
        run: |
          BUILD_DIR="build/${{ github.event.repository.name }}_${{ env.GITHUB_SHA_SHORT }}"
          mkdir $BUILD_DIR
          ./godot --headless --verbose --export-release "Linux" "$BUILD_DIR/${{ github.event.repository.name }}.x86_64"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v6
        with:
          name: build_${{ env.GITHUB_SHA_SHORT }}
          path: build/
