name: Build

env:
  GODOT_VERSION: 4.5.1

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Restore Godot Install from Cache
        id: cache-godot
        uses: actions/cache@v5
        with:
          path: |
            godot
            ~/.local/share/godot/export_templates/
          key: ${{ runner.os }}-godot

      - name: Install Godot
        if: steps.cache-godot.outputs.cache-hit != 'true'
        run: |
          wget --progress=bar:force:noscroll "https://downloads.godotengine.org/?version=${{ env.GODOT_VERSION }}&flavor=stable&slug=linux.x86_64.zip&platform=linux.64" -O godot.zip
          unzip godot.zip
          mv Godot_v*-stable_linux.x86_64 godot
          wget --progress=bar:force:noscroll "https://downloads.godotengine.org/?version=${{ env.GODOT_VERSION }}&flavor=stable&slug=export_templates.tpz&platform=templates" -O templates.zip
          unzip templates.zip
          mkdir -p $HOME/.local/share/godot/export_templates/
          mv templates/ $HOME/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable/

      - name: Set GitHub Environment Variables
        run: |
          echo "GITHUB_SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Export Project for Linux
        run: |
          BUILD_DIR="build/linux/${{ github.event.repository.name }}_${{ env.GITHUB_SHA_SHORT }}"
          mkdir -p $BUILD_DIR
          ./godot --headless --verbose --export-release "Linux" "$BUILD_DIR/${{ github.event.repository.name }}.x86_64"
      - name: Upload Linux Build
        uses: actions/upload-artifact@v6
        with:
          name: build_linux_${{ env.GITHUB_SHA_SHORT }}
          path: build/linux/

      - name: Export Project for Windows
        run: |
          BUILD_DIR="build/windows/${{ github.event.repository.name }}_${{ env.GITHUB_SHA_SHORT }}"
          mkdir -p $BUILD_DIR
          ./godot --headless --verbose --export-release "Windows Desktop" "$BUILD_DIR/${{ github.event.repository.name }}.exe"
      - name: Upload Windows Build
        uses: actions/upload-artifact@v6
        with:
          name: build_windows_${{ env.GITHUB_SHA_SHORT }}
          path: build/windows/
