name: Build

env:
  GODOT_VERSION: 4.5.1

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Godot
        run: |
          wget "https://downloads.godotengine.org/?version=${{ env.GODOT_VERSION }}&flavor=stable&slug=linux.x86_64.zip&platform=linux.64" -O godot.zip
          unzip godot.zip
          mv Godot_v*-stable_linux.x86_64 godot
          ls -la
